### ISSUE TITLE
无效 loadFromResource

### ISSUE THREAD

**Issue by cssxsh** [diyigemt/group-dumper#1]
https://github.com/diyigemt/group-dumper/blob/8bf9c154696154a7e4712ee1dd62dfad44b8b291/src/main/kotlin/com/diyigemt/groupdumper/GroupDumper.kt#L21

**Comment by diyigemt** [comment]
没懂，能否详细一些

**Comment by cssxsh** [comment]
> 没懂，能否详细一些

这个方法的作用就是返回一个 JvmPluginDescription，而不是 JvmPluginDescriptionBuilder 的 dsl 函数

但是你却用在了 JvmPluginDescriptionBuilder dsl 里面

**Comment by diyigemt** [comment]
哦懂了，我复制歪了。感谢
